apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-staging
  #  namespace: zero-mall
  labels:
    app: user-svc
    release: staging
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: user-svc
      release: staging
  template:
    metadata:
      labels:
        app: user-svc
        version: v1.5
        release: staging
    spec:
      #      serviceAccountName: find-endpoints1
      containers:
        - name: user-svc
          image: registry.cn-hangzhou.aliyuncs.com/zero-mall/user-rpc:v1.4
          #        command: ["sleep", "999999"]
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]
          ports:
            - containerPort: 8001
          readinessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 50Mi
            limits:
              cpu: 300m
              memory: 100Mi
      #        volumeMounts:
      #        - name: timezone
      #          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

